

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dhion
 */
public class NovoJogoConfig extends javax.swing.JFrame {

    /**
     * Creates new form NovoJogoConfig
     */
    public NovoJogoConfig() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtJogador1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtJogador2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        cBoxRodadas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 730));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("Nome do Jogador \"X\"");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtJogador1.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        txtJogador1.setForeground(new java.awt.Color(255, 0, 0));
        txtJogador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJogador1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtJogador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 260, 50));

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Nome do Jogador \"O\"");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtJogador2.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        txtJogador2.setForeground(new java.awt.Color(51, 102, 255));
        txtJogador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJogador2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtJogador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 260, 50));

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Quantidade de Rodadas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 310, 60));

        btnNovo.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(0, 153, 153));
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foguete.png"))); // NOI18N
        btnNovo.setText("Iniciar Jogo");
        btnNovo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 300, 90));

        cBoxRodadas.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        cBoxRodadas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "5", "7", "9" }));
        cBoxRodadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxRodadasActionPerformed(evt);
            }
        });
        jPanel1.add(cBoxRodadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 150, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tic-tac-toe-gb36f1e330_1280.png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setPreferredSize(new java.awt.Dimension(600, 730));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 670, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
   
    
    
    private void txtJogador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJogador2ActionPerformed
        
        
    }//GEN-LAST:event_txtJogador2ActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
       Controle controle = new Controle();
       if(txtJogador1.getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"Informe o nome do 1º Jogador");
       }
       else if(txtJogador2.getText().isEmpty() ){
       JOptionPane.showMessageDialog(null,"Informe o nome do 2º Jogador");
       }
       else if(Integer.parseInt((String) cBoxRodadas.getSelectedItem())==0){
       JOptionPane.showMessageDialog(null,"Informe a quantidade de rodadas");
       }
       else if(txtJogador1.getText().equals(txtJogador2.getText())){
       JOptionPane.showMessageDialog(null,"Informe nomes diferentes para os jogadores");
       }
       else{
       controle.setJogadorX(txtJogador1.getText());
       controle.setJogadorY(txtJogador2.getText());
       controle.setRodadas(Integer.parseInt((String) cBoxRodadas.getSelectedItem()));
        Tela viw = new Tela();
        viw.preenchimento(controle);
        
       viw.setVisible(true);
       
       this.dispose();
       }
       
      
        
      
    }//GEN-LAST:event_btnNovoActionPerformed

    private void txtJogador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJogador1ActionPerformed
       
     
    }//GEN-LAST:event_txtJogador1ActionPerformed

    private void cBoxRodadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxRodadasActionPerformed
        
    }//GEN-LAST:event_cBoxRodadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoJogoConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoJogoConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoJogoConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoJogoConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoJogoConfig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovo;
    private javax.swing.JComboBox<String> cBoxRodadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtJogador1;
    private javax.swing.JTextField txtJogador2;
    // End of variables declaration//GEN-END:variables
}
