
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dhion
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
      
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public int vencedor[][];
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaPrincipal = new javax.swing.JPanel();
        jogoVelha = new javax.swing.JPanel();
        telaJogo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        painelResultados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jgX = new javax.swing.JLabel();
        jgY = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        telaPrincipal.setPreferredSize(new java.awt.Dimension(600, 600));
        telaPrincipal.setLayout(new java.awt.BorderLayout());

        jogoVelha.setBackground(new java.awt.Color(255, 255, 255));
        jogoVelha.setPreferredSize(new java.awt.Dimension(600, 400));
        jogoVelha.setLayout(new java.awt.GridLayout(0, 1, 0, 1));

        telaJogo.setOpaque(false);
        telaJogo.setPreferredSize(new java.awt.Dimension(600, 400));
        telaJogo.setLayout(new java.awt.GridLayout(0, 3, 0, 3));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton1.setContentAreaFilled(false);
        jButton1.setLabel("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        telaJogo.add(jButton1);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton2.setContentAreaFilled(false);
        jButton2.setLabel("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        telaJogo.add(jButton2);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jButton3.setContentAreaFilled(false);
        jButton3.setLabel("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        telaJogo.add(jButton3);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton4.setContentAreaFilled(false);
        jButton4.setLabel("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        telaJogo.add(jButton4);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5.setContentAreaFilled(false);
        jButton5.setLabel("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        telaJogo.add(jButton5);

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jButton6.setContentAreaFilled(false);
        jButton6.setLabel("");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        telaJogo.add(jButton6);

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jButton7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        jButton7.setContentAreaFilled(false);
        jButton7.setLabel("");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        telaJogo.add(jButton7);

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jButton8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jButton8.setContentAreaFilled(false);
        jButton8.setLabel("");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        telaJogo.add(jButton8);

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jButton9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jButton9.setContentAreaFilled(false);
        jButton9.setLabel("");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        telaJogo.add(jButton9);

        jogoVelha.add(telaJogo);

        telaPrincipal.add(jogoVelha, java.awt.BorderLayout.PAGE_START);

        painelResultados.setBackground(new java.awt.Color(255, 255, 255));
        painelResultados.setPreferredSize(new java.awt.Dimension(600, 200));
        painelResultados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("SCORE");
        painelResultados.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 60));
        painelResultados.add(jgX, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 120, 40));
        painelResultados.add(jgY, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, 40));

        jButton10.setText("jButton10");
        painelResultados.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        painelResultados.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, 60));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        painelResultados.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, 60));

        jLabel4.setText("jLabel4");
        painelResultados.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel5.setText("jLabel5");
        painelResultados.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        telaPrincipal.add(painelResultados, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 5256, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Controle cont = new Controle();
    NovoJogoConfig novo = new NovoJogoConfig();
    Jogador jogador = new Jogador();
   
    
    public void jogadorNome(){
    jgX.setText(jogador.getJgX());
    JOptionPane.showMessageDialog(null, cont.rodadas);
    jgY.setText(jogador.getJgY());
     JOptionPane.showMessageDialog(null, novo.jogadorY());
    
    }
    
    
    
    
    public void reset(){
        
    
        
    Tela btn = new Tela();
    btn.jButton1.setText("Teste");
    
    if(cont.contRodada == 9){
     JOptionPane.showMessageDialog(null, "Fim da Rodada");
    
    cont.fimRodada = true;
    btn.jButton1.setText("");
    btn.jButton2.setText("");
    btn.jButton3.setText("");
    btn.jButton4.setText("");
    btn.jButton5.setText("");
    btn.jButton6.setText("");
    btn.jButton7.setText("");
    btn.jButton8.setText("");
    btn.jButton9.setText("");
    
    btn.jButton1.setEnabled(true);
    btn.jButton2.setEnabled(true);
    btn.jButton3.setEnabled(true);
    btn.jButton4.setEnabled(true);
    btn.jButton5.setEnabled(true);
    btn.jButton6.setEnabled(true);
    btn.jButton7.setEnabled(true);
    btn.jButton8.setEnabled(true);
    btn.jButton9.setEnabled(true);
    
   
     
     
     if(cont.fimRodada){
        jButton1.setText("");
        jButton1.setEnabled(true);
        jButton2.setText("");
        jButton2.setEnabled(true);
        jButton3.setText("");
        jButton3.setEnabled(true);
        jButton4.setText("");
        jButton4.setEnabled(true);
        jButton5.setText("");
        jButton5.setEnabled(true);
        jButton6.setText("");
        jButton6.setEnabled(true);
        jButton7.setText("");
        jButton7.setEnabled(true);
        jButton8.setText("");
        jButton8.setEnabled(true);
        jButton9.setText("");
        jButton9.setEnabled(true);
        cont.fimRodada = false;
        cont.contRodada = 0;
        }
      
     
    }
    
           
    
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cont.contRodada++;
        jButton1.setText(cont.JogadorDaVez());
        if(cont.JogadorDaVez() == "X"){
        jButton1.setForeground(Color.red);
        }
        else{
        jButton1.setForeground(Color.blue);
        }
        jButton1.setEnabled(false);
        
         reset();
        String teste = novo.jogadorx;
        JOptionPane.showMessageDialog(null, teste);
         jogadorNome();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      cont.contRodada++;
      jButton2.setText(cont.JogadorDaVez());
      if(cont.JogadorDaVez() == "X"){
        jButton2.setForeground(Color.red);
        }
        else{
        jButton2.setForeground(Color.blue);
        }
      jButton2.setEnabled(false);
      reset();
      jogadorNome();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       cont.contRodada++;
      jButton3.setText(cont.JogadorDaVez());
      if(cont.JogadorDaVez() == "X"){
        jButton3.setForeground(Color.red);
        }
        else{
        jButton3.setForeground(Color.blue);
        }
      jButton3.setEnabled(false);
      reset();
      jogadorNome();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      cont.contRodada++;
      jButton4.setText(cont.JogadorDaVez());
      if(cont.JogadorDaVez() == "X"){
        jButton4.setForeground(Color.red);
        }
        else{
        jButton4.setForeground(Color.blue);
        }
      jButton4.setEnabled(false);
      reset();
      jogadorNome();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       cont.contRodada++;
      jButton5.setText(cont.JogadorDaVez());
      if(cont.JogadorDaVez() == "X"){
        jButton5.setForeground(Color.red);
        }
        else{
        jButton5.setForeground(Color.blue);
        }
      jButton5.setEnabled(false);
      reset();
      jogadorNome();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       cont.contRodada++;
      jButton6.setText(cont.JogadorDaVez());
      if(cont.JogadorDaVez() == "X"){
        jButton6.setForeground(Color.red);
        }
        else{
        jButton6.setForeground(Color.blue);
        }
      jButton6.setEnabled(false);
      reset();
      jogadorNome();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       cont.contRodada++;
      jButton7.setText(cont.JogadorDaVez());
      if(cont.JogadorDaVez() == "X"){
        jButton7.setForeground(Color.red);
        }
        else{
        jButton7.setForeground(Color.blue);
        }
      jButton7.setEnabled(false);
      reset();
      jogadorNome();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       cont.contRodada++;
      jButton8.setText(cont.JogadorDaVez());
      if(cont.JogadorDaVez() == "X"){
        jButton8.setForeground(Color.red);
        }
        else{
        jButton8.setForeground(Color.blue);
        }
      jButton8.setEnabled(false);
      reset();
      jogadorNome();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        cont.contRodada++;
      jButton9.setText(cont.JogadorDaVez());
      if(cont.JogadorDaVez() == "X"){
        jButton9.setForeground(Color.red);
        }
        else{
        jButton9.setForeground(Color.blue);
        }
      jButton9.setEnabled(false);
      reset();
      jogadorNome();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JButton getjButton3() {
        return jButton3;
    }

    public void setjButton3(JButton jButton3) {
        this.jButton3 = jButton3;
    }

    public JButton getjButton4() {
        return jButton4;
    }

    public void setjButton4(JButton jButton4) {
        this.jButton4 = jButton4;
    }

    public JButton getjButton5() {
        return jButton5;
    }

    public void setjButton5(JButton jButton5) {
        this.jButton5 = jButton5;
    }

    public JButton getjButton6() {
        return jButton6;
    }

    public void setjButton6(JButton jButton6) {
        this.jButton6 = jButton6;
    }

    public JButton getjButton7() {
        return jButton7;
    }

    public void setjButton7(JButton jButton7) {
        this.jButton7 = jButton7;
    }

    public JButton getjButton8() {
        return jButton8;
    }

    public void setjButton8(JButton jButton8) {
        this.jButton8 = jButton8;
    }

    public JButton getjButton9() {
        return jButton9;
    }

    public void setjButton9(JButton jButton9) {
        this.jButton9 = jButton9;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    public javax.swing.JButton jButton7;
    public javax.swing.JButton jButton8;
    public javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel jgX;
    private javax.swing.JLabel jgY;
    private javax.swing.JPanel jogoVelha;
    private javax.swing.JPanel painelResultados;
    private javax.swing.JPanel telaJogo;
    private javax.swing.JPanel telaPrincipal;
    // End of variables declaration//GEN-END:variables
}
